name: Telegram Bot Runner

on:
  workflow_dispatch:

concurrency:
  group: telegram-bot-runner
  cancel-in-progress: true   

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install python-telegram-bot httpx

      - name: Run Telegram Bot
        timeout-minutes: 360
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GTHUB_TOKEN: ${{ secrets.GTHUB_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
        run: |
          python Telegram_bot.py
          
